/* Design-only synthetic fixtures. No network, production records or persistent writes. */
'use strict';
const $ = id => document.getElementById(id);
const esc = text => String(text ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const row = (title, context, status, count, unit, action, route, note='',tone='') => ({title,context,status,count,unit,action,route,note,tone});
const lane = (label, unit, rows, hint='') => ({label,unit,rows,hint});
const roles = {
  SAMPLE_RECEPTION: {name:'Sample reception',person:'Lucia · Intake desk',title:'Reception',subtitle:'Receive arriving samples, finish an intake, or follow up a problem.',eyebrow:'At the intake desk',scope:'Demonstration lab · Guatemala',primary:'New intake',primaryRoute:'/reception',primaryNote:'Project samples, external samples and consignments begin in the same reception console. Scan or find the sample, verify the request and custody, then explicitly receive it.',nav:['Home','Samples','Reception','Reports'],priority:['attention','drafts','expected','received'],railTitle:'Keep arrival separate from preparation',rail:['Expected records have not arrived. They are searchable here, but do not appear as drying or preparation work.','A saved intake stays a draft until receipt is confirmed. Resume it with its project, field location and analysis request intact.'],shortcuts:['Open reception','Find a sample','Today’s receipts'],lanes:{
    attention:lane('Needs attention','samples',[row('DEMO-021','External sample · Intake 10:14','Container damaged',1,'sample','Inspect','/samples/demo-021?tab=request','Record the condition and an authorized intake disposition before proceeding.','problem')]),
    drafts:lane('My drafts','drafts',[row('FIELD-1042','Soil survey · 10–20 cm','Saved 09:25',1,'draft','Resume','/reception?sampleId=demo-1042','Location is recorded from field provenance. Resume the existing draft; do not create another sample.'),row('FIELD-1043','Soil survey · 20–40 cm','Saved 09:29',1,'draft','Resume','/reception?sampleId=demo-1043')]),
    expected:lane('Expected samples','samples',Array.from({length:18},(_,i)=>row(`FIELD-${1050+i}`,'Soil survey · Manifest DEMO-06','Not received',1,'sample','Open intake',`/reception?sampleId=demo-${1050+i}`,'Field registration is not physical receipt. No arrival date has been scheduled.','waiting')),'Field records awaiting receipt; not a processing backlog'),
    received:lane('Received today','samples',[row('DEMO-018','FIELD-1038 · Accepted 09:12','Accepted',1,'sample','View receipt','/samples/demo-018?tab=request'),row('DEMO-019','FIELD-1039 · Accepted 09:18','Accepted',1,'sample','View receipt','/samples/demo-019?tab=request'),row('DEMO-021','External sample · Received 10:14','Awaiting disposition',1,'sample','Inspect','/samples/demo-021?tab=request','','waiting')],'Physical receipt, including arrivals awaiting a disposition')
  }},
  LAB_TECHNICIAN:{name:'Laboratory technician',person:'Elena · Soil analysis',title:'My bench',subtitle:'Continue a run or open the next method worksheet.',eyebrow:'Your assigned laboratory work',scope:'Demonstration lab · Guatemala',primary:'Open workbench',primaryRoute:'/workbench',primaryNote:'The workbench holds checklists, method worksheets, spectral import, saved drafts and the review-before-submit step.',nav:['Home','Workbench','My work','Samples','Reports'],priority:['returned','continue','ready','submit','waiting'],railTitle:'Work through one method at a time',rail:['Keep sample positions and the instrument run together. A worksheet can hold forty pH determinations without forty separate cards.','Drying and preparation use checklists. Spectroscopy uses linked spectra. Texture is entered and checked as one group.'],shortcuts:['Open workbench','View activity receipts','Find a sample'],lanes:{
    returned:lane('Returned','determinations',[row('pH in water','Run PH-DEMO-05 · SOP revision 3','Repeat requested',2,'determinations','Review reason','/workbench?runId=demo-ph-05','Reviewer: duplicate readings differed beyond this method’s configured tolerance. Open the current returned attempts and preserve the original values.','problem')]),
    continue:lane('Continue','runs',[row('pH in water','Run PH-DEMO-06 · 40 samples · SOP revision 3','26 of 40 saved',1,'run','Continue run','/workbench?runId=demo-ph-06','Fourteen rows remain. The saved run retains sample positions, instrument and QC context.')]),
    ready:lane('Ready work','tasks',[row('pH in water','Water suspension · SOP revision 3','Ready to record',40,'determinations','Open worksheet','/workbench?analysis=PH_H2O&methodologyId=demo-ph-water&revision=3&queue=bench.ready','Forty assigned, received and prepared samples. Select or confirm an eligible instrument before recording.'),row('Electrical conductivity','Soil / water 1:5 · SOP revision 2','Ready to record',12,'determinations','Open worksheet','/workbench?analysis=EC&methodologyId=demo-ec-15&revision=2&queue=bench.ready'),row('Particle-size distribution','Hydrometer · SOP revision 4','Ready to record',8,'determinations','Open group','/workbench?analysis=TEXTURE&methodologyId=demo-texture&revision=4&queue=bench.ready','One determination per sample. Sand, silt and clay are checked together, with the configured closure tolerance and derived texture class.'),row('MIR spectroscopy','DRIFTS · SOP revision 2','Ready for spectra',10,'determinations','Open spectral work','/workbench?analysis=SPEC_MIR&methodologyId=demo-mir&revision=2&queue=bench.ready','Upload or link exported spectra with sample matching and QC evidence. A reflectance number is not the spectrum.'),row('Drying','Operational checklist · Air drying','Ready for checklist',6,'checklists','Open checklist','/workbench?analysis=DRYING&queue=bench.ready','Record required preparation evidence through a checklist, not a determination-value box.')],'Assigned work whose prerequisites allow the next entry step'),
    submit:lane('To submit','determinations',[row('Electrical conductivity','Run EC-DEMO-03 · 12 samples','Ready for your review',12,'determinations','Review and submit','/workbench?runId=demo-ec-03&queue=bench.toSubmit','Check the completed evidence and selected rows in Workbench before submitting. Nothing is sent from this dashboard.')]),
    waiting:lane('Waiting','tasks',[row('Sample preparation','6 samples · Oven rack B','Waiting for drying',6,'checklists','See dependency','/workbench?analysis=PREPARATION&queue=bench.waiting','Drying evidence is not complete. The worksheet remains locked until the prerequisite is satisfied.','waiting'),row('pH in water','5 samples · SOP revision 3','Waiting for preparation',5,'determinations','See dependency','/workbench?analysis=PH_H2O&queue=bench.waiting','Sample preparation must finish before any result draft is entered.','waiting')])
  }},
  LAB_MANAGER:{name:'Laboratory manager',person:'Rafael · Lab manager',title:'Laboratory work',subtitle:'Resolve a blocker, review submitted work, or assign the next batch.',eyebrow:'Today in the laboratory',scope:'Demonstration lab · Guatemala',primary:'Open manager queue',primaryRoute:'/manager-queue',primaryNote:'The manager queue opens the highest-priority nonempty decision lane. An intentional lane stays selected as new work arrives.',nav:['Home','Manager queue','Samples','Reception','Staff','Reports'],priority:['exceptions','review','approve','assign','intake'],railTitle:'A clear handoff to the bench',rail:['Assign work by method and available staff. The instrument run and its QC positions stay in Workbench.','A sample is ready for final approval only after all required work, evidence and QC are resolved. Reception or preparation alone cannot qualify it.'],shortcuts:['Open manager queue','Review staff workload','Open audit history'],lanes:{
    exceptions:lane('Needs a decision','exceptions',[row('Electrical conductivity','Run EC-DEMO-02 · 12 affected samples','QC needs a decision',1,'exception','Inspect QC','/manager-queue?lane=review&queue=manager.exceptions','The control failed the method’s configured rule. Review the actual QC evidence and disposition before accepting affected work.','problem')]),
    review:lane('Submitted work','samples',[row('DEMO-028','pH in water · Elena · 09:41','Ready for review',1,'sample','Review','/samples/demo-028?tab=review&submissionId=demo-sub-28'),row('DEMO-029','Particle-size distribution · Elena · 09:43','Ready for review',1,'sample','Review','/samples/demo-029?tab=review&submissionId=demo-sub-29','Sand, silt and clay are reviewed together with the derived class.'),row('DEMO-030','MIR spectroscopy · Luis · 10:01','Ready for review',1,'sample','Review','/samples/demo-030?tab=review&submissionId=demo-sub-30','Review linked current spectra and QC; distinguish any predictions from reference measurements.')],'Samples with current submitted work; one sample may contain several submissions'),
    approve:lane('Final approval','samples',[row('DEMO-026','All ordered analyses accepted · QC resolved','Ready for final check',1,'sample','Open final review','/samples/demo-026?tab=review','Final approval is an explicit action after inspection. Publishing the controlled report is a separate step.'),row('DEMO-027','Spectral-only order · Validated evidence','Ready for final check',1,'sample','Open final review','/samples/demo-027?tab=review')]),
    assign:lane('Assign work','tasks',[row('pH in water','SOP revision 3 · 40 samples','Unassigned',40,'determinations','Assign by method','/manager-queue?lane=assign&analysis=PH_H2O'),row('Particle-size distribution','Hydrometer · 8 samples','Unassigned',8,'determinations','Assign by method','/manager-queue?lane=assign&analysis=TEXTURE'),row('Sample preparation','12 samples · Drying complete','Unassigned',12,'checklists','Assign preparation','/manager-queue?lane=assign&analysis=PREPARATION')]),
    intake:lane('Intake acceptance','samples',[row('DEMO-040','Soil survey · Physical receipt 10:16','Awaiting acceptance',1,'sample','Inspect intake','/manager-queue?lane=intake&sampleId=demo-040','','waiting')])
  }},
  MASTER_USER:{name:'National master user',person:'Sofia · National programme',title:'Laboratories',subtitle:'Follow the work across your laboratories and open a lab when a decision is needed.',eyebrow:'Programme oversight',scope:'Demonstration national programme · Guatemala',primary:'Choose a laboratory',primaryRoute:'/manager-queue?labId=demo-lab-1',primaryNote:'Choose only from authorized labs. Operational counts and commands must be scoped to the selected lab and reauthorized at the destination.',nav:['Home','Laboratories','Projects','Samples','Reports'],priority:['exceptions','active','released'],railTitle:'One scope, wherever you continue',rail:['The national view is limited to your granted laboratories and projects. Each laboratory uses its own local day for lab activity.','Approval authority still depends on the selected laboratory and the current evidence.'],shortcuts:['Choose a laboratory','View programme reports','Open project records'],lanes:{
    exceptions:lane('Needs attention','laboratories',[row('Demonstration laboratory 1','Guatemala · 12 samples affected','One QC decision pending',1,'laboratory','Open laboratory','/manager-queue?labId=demo-lab-1&lane=review','','waiting')]),
    active:lane('Active laboratories','laboratories',[row('Demonstration laboratory 1','73 received samples in active work','3 samples in review',1,'laboratory','View work','/samples?queue=lab.processing&labId=demo-lab-1'),row('Demonstration laboratory 2','28 received samples in active work','4 samples in review',1,'laboratory','View work','/samples?queue=lab.processing&labId=demo-lab-2')]),
    released:lane('Released reports','reports',[row('Soil survey · September','Demonstration laboratory 1','Current published report',1,'report','Open report','/result-reports?reportId=demo-r-01'),row('Soil survey · September','Demonstration laboratory 2','Current published report',1,'report','Open report','/result-reports?reportId=demo-r-02')])
  }},
  PROJECT_MANAGER:{name:'Project manager',person:'Ana · Project coordination',title:'Project progress',subtitle:'See what has arrived, what is waiting, and which results are available.',eyebrow:'Your assigned projects',scope:'Demonstration soil survey · Project access',primary:'Open project records',primaryRoute:'/samples?projectId=demo-survey',primaryNote:'The sample list keeps this project filter and the same authorized record set. Project access does not grant laboratory approval authority.',nav:['Home','Projects','Samples','Reports','Maps'],priority:['attention','active','expected','released'],railTitle:'Progress with a clear meaning',rail:['Expected means registered but not received. Active work means the laboratory has received and accepted the material.','Published reports are available separately from analyses that are still being reviewed.'],shortcuts:['Open project records','View released reports','View field map'],lanes:{
    attention:lane('Needs follow-up','samples',[row('FIELD-1080','Soil survey · Request DEMO-12','Custody information needed',1,'sample','Inspect request','/samples/demo-1080?tab=request','','waiting')]),
    active:lane('At the laboratory','samples',Array.from({length:6},(_,i)=>row(`DEMO-${String(31+i).padStart(3,'0')}`,'Soil survey · Laboratory 1',i<3?'Analysis underway':'Under review',1,'sample','View progress',`/samples/demo-${31+i}`))),
    expected:lane('Not received','samples',[row('FIELD-1081','Soil survey · Manifest DEMO-12','Not received',1,'sample','View field record','/samples/demo-1081','','waiting'),row('FIELD-1082','Soil survey · Manifest DEMO-12','Not received',1,'sample','View field record','/samples/demo-1082','','waiting')]),
    released:lane('Published reports','reports',[row('DEMO-011','Soil survey · Report version 1','Published',1,'report','Open report','/result-reports?reportId=demo-r-11')])
  }},
  AUDIT_USER:{name:'Quality and audit officer',person:'Marta · Quality review',title:'Quality review',subtitle:'Inspect exceptions and follow the evidence through its recorded history.',eyebrow:'Read-only quality oversight',scope:'Demonstration lab · Authorized audit scope',primary:'Open audit history',primaryRoute:'/admin/audit',primaryNote:'Inspect the authorized audit history. This role cannot change results, waive QC, approve analyses or publish a report.',nav:['Home','Quality review','Samples','Audit history','Reports'],priority:['exceptions','qc','history'],railTitle:'Evidence first',rail:['An alert points to its source evidence and responsible role. It is resolved in the controlled laboratory workflow.','A later amendment does not erase an earlier signed review or report version.'],shortcuts:['Open audit history','Inspect report history','View quality records'],lanes:{
    exceptions:lane('Evidence exceptions','samples',[row('DEMO-008','Historical accepted result','Evidence needs verification',1,'sample','Inspect history','/samples/demo-008?tab=history','The accepted legacy status has no linked current analytical evidence. It must not count as a valid release.','problem')]),
    qc:lane('QC requiring attention','batches',[row('EC-DEMO-02','Electrical conductivity · 12 samples','QC failed',1,'batch','Inspect evidence','/qa?batchId=demo-ec-02','Read-only inspection; the authorized manager handles disposition.','problem'),row('PH-DEMO-06','pH in water · 40 samples','QC pending',1,'batch','Inspect evidence','/qa?batchId=demo-ph-06','Missing QC evidence is pending, not a pass.','waiting')]),
    history:lane('Recent amendments','amendments',[row('DEMO-006','Controlled amendment · Report versions 1 → 2','Reason recorded',1,'amendment','View versions','/samples/demo-006?tab=history')])
  }},
  SURVEYOR:{name:'Field surveyor',person:'Diego · Field team',title:'Field samples',subtitle:'Finish field details and follow your samples into the laboratory.',eyebrow:'Your field registrations',scope:'Demonstration soil survey · Authorized field records',primary:'Open field records',primaryRoute:'/samples?queue=field.mine&projectId=demo-survey',primaryNote:'Only owned or explicitly permitted field records are shown. Existing provenance editing requires the correct object permission; no reception action is granted by this shortcut.',nav:['Home','Field samples','Maps'],priority:['incomplete','expected','received'],railTitle:'Keep the field and lab identities together',rail:['A valid coordinate at zero latitude or longitude is still a coordinate. Missing location is shown only when the record was loaded successfully.','The field registration and handover are separate from the laboratory’s physical receipt.'],shortcuts:['Open field records','View field map','Check laboratory receipts'],lanes:{
    incomplete:lane('Details to complete','records',[row('FIELD-1090','Soil survey · Collection 5 September','Depth not recorded',1,'record','View field record','/samples/demo-1090?tab=request','Continue through the authorized field/provenance editor if this account owns the record.','waiting')]),
    expected:lane('Awaiting receipt','samples',[row('FIELD-1081','Consignment DEMO-12 · Handover recorded','Not received by lab',1,'sample','View custody','/samples/demo-1081?tab=request','','waiting'),row('FIELD-1082','Consignment DEMO-12 · Handover recorded','Not received by lab',1,'sample','View custody','/samples/demo-1082?tab=request','','waiting')]),
    received:lane('Receipt confirmed','samples',[row('FIELD-1038','Lab sample DEMO-018 · 09:12 today','Receipt confirmed',1,'sample','View receipt','/samples/demo-018?tab=request')])
  }},
  EXTERNAL_VIEWER:{name:'External partner',person:'Sam · Project partner',title:'My results',subtitle:'Open the laboratory reports available to your project.',eyebrow:'Published results',scope:'Demonstration project · Restricted report access',primary:'Browse reports',primaryRoute:'/result-reports?projectId=demo-survey&status=PUBLISHED',primaryNote:'Only current published reports granted to this account are available. Downloading an existing report does not generate or publish another version.',nav:['Home','Reports'],priority:['released'],railTitle:'Current laboratory reports',rail:['Each report shows its issue date and version. If a report is replaced, the current authorized version is offered.','Internal work notes and unpublished laboratory data are not included in this view.'],shortcuts:['Browse reports'],lanes:{released:lane('Available reports','reports',[row('DEMO-011','Soil survey · Issued 5 September · Version 1','Published',1,'report','Open report','/result-reports?reportId=demo-r-11'),row('DEMO-012','Soil survey · Issued 5 September · Version 2','Published',1,'report','Open report','/result-reports?reportId=demo-r-12'),row('DEMO-013','Soil survey · Issued 6 September · Version 1','Published',1,'report','Open report','/result-reports?reportId=demo-r-13')])}},
  VIEWER:{name:'General viewer',person:'Alex · Sample tracking',title:'Sample tracking',subtitle:'Follow the samples and published reports you have access to.',eyebrow:'Read-only sample access',scope:'Demonstration lab · Permitted records',primary:'Browse samples',primaryRoute:'/samples',primaryNote:'Read-only sample tracking; access restrictions also apply to direct URLs and reports.',nav:['Home','Samples','Reports'],priority:['active','expected','released'],railTitle:'See the stage, then the record',rail:['Samples that have not arrived stay separate from samples in laboratory work.','Only a published report is presented as a released result.'],shortcuts:['Browse samples','View released reports'],lanes:{active:lane('In laboratory work','samples',[row('DEMO-031','Soil survey · Received 6 September','Preparation underway',1,'sample','View progress','/samples/demo-031'),row('DEMO-032','Soil survey · Received 5 September','Under review',1,'sample','View progress','/samples/demo-032')]),expected:lane('Not received','samples',[row('FIELD-1082','Soil survey · Field registration','Not received',1,'sample','View status','/samples/demo-1082','','waiting')]),released:lane('Published reports','reports',[row('DEMO-011','Soil survey · Version 1','Published',1,'report','Open report','/result-reports?reportId=demo-r-11')])}},
  SUPER_ADMIN:{name:'Super administrator',person:'Y. Admin · System administration',title:'System overview',subtitle:'Keep laboratory access and configuration in working order.',eyebrow:'Administration',scope:'All authorized laboratories · Global administration',primary:'Choose a laboratory',primaryRoute:'/admin/labs',primaryNote:'Choose an authorized laboratory for its operational view. Global administrative counts must never carry a single-lab heading.',nav:['Home','Laboratories','Users','Configuration','Audit history'],priority:['configuration','labs','activity'],railTitle:'Report what is known',rail:['Configuration problems come from actual validation results. Missing telemetry is “not checked”, not a green healthy status.','Laboratory activity is opened in an explicit lab scope. Administrative access does not remove evidence requirements.'],shortcuts:['Open analysis configuration','Manage laboratories','Open audit history'],lanes:{configuration:lane('Configuration issues','issues',[row('Demonstration laboratory 2','Local dates cannot be calculated','Timezone not configured',1,'issue','Open laboratory','/admin/labs?labId=demo-lab-2','Configure an IANA timezone before showing this laboratory’s daily metrics.','waiting'),row('Particle-size distribution','Demonstration laboratory 3 · Catalogue','Method unavailable',1,'issue','Inspect configuration','/admin/methods?analysis=TEXTURE&labId=demo-lab-3','The configured method is not available to new orders. Preserve existing order revisions while correcting configuration.','problem')]),labs:lane('Laboratories','laboratories',[row('Demonstration laboratory 1','Guatemala · America/Guatemala','Open lab work',1,'laboratory','View laboratory','/manager-queue?labId=demo-lab-1'),row('Demonstration laboratory 2','Guatemala · Timezone missing','Configuration required',1,'laboratory','View laboratory','/admin/labs?labId=demo-lab-2','','waiting'),row('Demonstration laboratory 3','Guatemala · America/Guatemala','Open lab work',1,'laboratory','View laboratory','/manager-queue?labId=demo-lab-3')]),activity:lane('Configuration changes','events',[row('Method revision updated','Demonstration laboratory 1 · 09:04','Audit recorded',1,'event','Inspect change','/admin/audit?entity=ANALYSIS')])}}
};
let currentRole='LAB_TECHNICIAN',currentLane='',page=1,query='',scenario='normal';
const PAGE_SIZE=5;
const total = rows => rows.reduce((n,r)=>n+r.count,0);
function laneRows(key){if(scenario==='empty'||scenario==='error')return [];if(scenario==='blocked'&&currentRole==='LAB_TECHNICIAN'&&key!=='waiting')return [];return roles[currentRole].lanes[key]?.rows||[];}
function defaultLane(){const r=roles[currentRole];return r.priority.find(k=>laneRows(k).length)||r.priority[0];}
function openPreview(title,route,note,record){
  $('detail-kind').textContent=record?'Work detail':'Continue to workspace';$('detail-title').textContent=title;
  let content=`<p>${esc(note||'Open the current record with the same laboratory and queue context. Eligibility and permissions are checked again there.')}</p>`;
  if(record){content+=`<div class="detail-facts"><div><small>Context</small>${esc(record.context)}</div><div><small>Current state</small><span class="tag ${record.tone}">${esc(record.status)}</span></div><div><small>Work represented</small>${record.count} ${esc(record.unit)}</div><div><small>Next step</small>${esc(record.action)}</div></div>`;
    if(currentRole==='LAB_TECHNICIAN'&&record.title==='pH in water'&&/40|Continue run/.test(record.context+' '+record.count+' '+record.action)){
      content+='<h3>Worksheet sample positions</h3><p>Forty sample rows travel together into the method worksheet. QC positions are added according to the configured run.</p><div class="mini-table"><table><thead><tr><th>Position</th><th>Sample / field ID</th><th>Entry state</th></tr></thead><tbody>';
      for(let i=1;i<=40;i++)content+=`<tr><td>${String(i).padStart(2,'0')}</td><td>DEMO-${String(100+i).padStart(3,'0')}<small>FIELD-${2000+i}</small></td><td>${currentLane==='continue'&&i<=26?'Draft saved':'Ready for entry'}</td></tr>`;
      content+='</tbody></table></div>';
    }
  }
  content+=`<small class="preview-route">Implementation preview: destination to wire and verify<br>${esc(route)}</small>`;
  $('detail-body').innerHTML=content;$('detail').showModal();
}
function renderTable(){
  const l=roles[currentRole].lanes[currentLane];const rows=laneRows(currentLane).filter(r=>(r.title+' '+r.context+' '+r.status).toLowerCase().includes(query.toLowerCase()));const pages=Math.max(1,Math.ceil(rows.length/PAGE_SIZE));page=Math.min(page,pages);
  $('queue-title').textContent=l.label;$('queue-subtitle').textContent=l.hint||`${l.unit.charAt(0).toUpperCase()+l.unit.slice(1)} in your current scope`;
  $('prev').disabled=page===1;$('next').disabled=page>=pages;
  if(scenario==='error'){$('table-wrap').innerHTML='<div class="empty"><h3>We could not load your work</h3><p>Your records have not changed. Try refreshing to check the current queue.</p><button id="retry">Try again</button></div>';$('retry').onclick=()=>{$('scenario').value='normal';changeScenario();};$('row-count').textContent='Counts unavailable';return;}
  if(!rows.length){$('table-wrap').innerHTML=`<div class="empty"><h3>${query?'No matching records':'Nothing waiting here'}</h3><p>${query?'Try a sample ID, parameter name or a different search.':'There is no work in this queue. You can choose another queue or return when new work arrives.'}</p></div>`;$('row-count').textContent=`0 ${l.unit}`;return;}
  const visible=rows.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);$('table-wrap').innerHTML='<table><thead><tr><th>Work / sample</th><th>State</th><th>Count</th><th>Next step</th></tr></thead><tbody>'+visible.map((r,i)=>`<tr><td><strong>${esc(r.title)}</strong><small>${esc(r.context)}</small></td><td><span class="tag ${r.tone}">${esc(r.status)}</span></td><td>${r.count}<small>${esc(r.unit)}</small></td><td><button class="row-action" data-row="${i}">${esc(r.action)} <span aria-hidden="true">→</span></button></td></tr>`).join('')+'</tbody></table>';
  document.querySelectorAll('[data-row]').forEach(b=>b.onclick=()=>{const r=visible[Number(b.dataset.row)];openPreview(r.title,r.route,r.note,r);});
  $('row-count').textContent=`${(page-1)*PAGE_SIZE+1}–${Math.min(page*PAGE_SIZE,rows.length)} of ${rows.length} ${rows.some(r=>r.count>1)?'groups':'records'} · ${total(rows)} ${l.unit}${scenario==='stale'?' · last saved view':''}`;
}
function renderQueues(){const r=roles[currentRole];$('summaries').innerHTML=Object.entries(r.lanes).slice(0,4).map(([k,l])=>`<button class="summary ${k===currentLane?'selected':''}" data-lane="${k}" aria-pressed="${k===currentLane}"><span class="label">${esc(l.label)}</span><span class="value">${scenario==='error'?'—':total(laneRows(k))}</span><small>${scenario==='error'?'Unavailable':esc(l.unit)}</small></button>`).join('');
  $('summaries').style.gridTemplateColumns=Object.keys(r.lanes).length===1?'minmax(0,1fr)':'';
  $('lanes').innerHTML=Object.entries(r.lanes).map(([k,l])=>`<button data-lane="${k}" aria-pressed="${k===currentLane}">${esc(l.label)}<span class="count">${scenario==='error'?'—':total(laneRows(k))}</span></button>`).join('');
  document.querySelectorAll('[data-lane]').forEach(b=>b.onclick=()=>{currentLane=b.dataset.lane;page=1;renderQueues();renderTable();});renderTable();}
function shortcutRoute(label){if(/workbench|receipts/i.test(label)&&currentRole==='LAB_TECHNICIAN')return '/workbench';if(/reception/i.test(label))return '/reception';if(/audit/i.test(label))return '/admin/audit';if(/method|analysis configuration/i.test(label))return '/admin';if(/map/i.test(label))return '/maps';if(/staff/i.test(label))return '/users';if(/report/i.test(label))return '/result-reports';if(/laborator/i.test(label))return currentRole==='SUPER_ADMIN'?'/admin/labs':'/manager-queue';if(/manager/i.test(label))return '/manager-queue';if(/quality/i.test(label))return '/qa';return '/samples';}
function render(){const r=roles[currentRole];$('role-label').textContent=r.name;$('person').textContent=r.person;$('initials').textContent=r.person.slice(0,1);$('scope').textContent=r.scope;$('eyebrow').textContent=r.eyebrow;$('title').textContent=r.title;$('subtitle').textContent=r.subtitle;$('primary').textContent=r.primary;$('primary').onclick=()=>openPreview(r.primary,r.primaryRoute,r.primaryNote);$('rail-title').textContent=r.railTitle;$('rail-copy').innerHTML=r.rail.map((p,i)=>`<p class="${i?'note':''}">${esc(p)}</p>`).join('');$('shortcuts').innerHTML=r.shortcuts.map(s=>`<button data-shortcut="${esc(s)}">${esc(s)} <span aria-hidden="true">→</span></button>`).join('');document.querySelectorAll('[data-shortcut]').forEach(b=>b.onclick=()=>openPreview(b.dataset.shortcut,shortcutRoute(b.dataset.shortcut),'Continue in the existing workspace. The implementation must preserve the selected scope and check access at the destination.'));
  $('nav').innerHTML=r.nav.map((n,i)=>`<button class="${i===0?'active':''}" data-nav="${esc(n)}" ${i===0?'aria-current="page"':''}>${esc(n)}</button>`).join('');document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{if(b.dataset.nav==='Home'){currentLane=defaultLane();query='';$('search').value='';renderQueues();return;}openPreview(b.dataset.nav,shortcutRoute(b.dataset.nav),'Continue in the authorized workspace. This design preview does not navigate to production.');});
  $('freshness').textContent=scenario==='error'?'Not connected':scenario==='stale'?'Could not refresh · Showing 09:32':'Updated just now';
  $('notice').innerHTML=scenario==='stale'?'<div class="notice">We could not refresh this view. These figures are from 09:32. The source record will be checked again when you continue.</div>':scenario==='error'?'<div class="notice error">Current counts are unavailable. A blank count does not mean there is no work.</div>':scenario==='blocked'?`<div class="notice">${currentRole==='LAB_TECHNICIAN'?'These assigned samples are waiting for drying or preparation. Result entry is locked; open a dependency to see what is needed.':'Prerequisite locks are demonstrated in the technician view. This role retains its own authorized queues.'}</div>`:'';renderQueues();}
function changeScenario(){scenario=$('scenario').value;currentLane=defaultLane();page=1;query='';$('search').value='';render();}
$('role').innerHTML=Object.entries(roles).map(([k,r])=>`<option value="${k}">${r.name}</option>`).join('');$('role').value=currentRole;$('role').onchange=()=>{currentRole=$('role').value;changeScenario();};$('scenario').onchange=changeScenario;$('search').oninput=()=>{query=$('search').value;page=1;renderTable();};$('prev').onclick=()=>{page--;renderTable();};$('next').onclick=()=>{page++;renderTable();};$('refresh').onclick=()=>{$('scenario').value='normal';scenario='normal';render();};$('theme').onclick=()=>{const active=document.body.classList.toggle('dark');$('theme').setAttribute('aria-pressed',String(active));$('theme').textContent=active?'Light appearance':'Dark appearance';};$('close').onclick=$('done').onclick=()=>{$('detail').close();};currentLane=defaultLane();render();
window.dashboardPrototype={roles,getState:()=>({currentRole,currentLane,scenario,page}),laneRows};
