/* Builds this isolated design package. Does not import or execute LIMS services. */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const cp = require('child_process');
const dir = __dirname, root = path.resolve(dir, '../..');
const groups = require('./inventory-source.cjs');
const examples = require('./guide-examples.json');
const write = (name, body) => fs.writeFileSync(path.join(dir, name), typeof body === 'string' ? body : JSON.stringify(body, null, 2) + '\n');
const roles = [
 ['LAB_TECHNICIAN','Laboratory technician',['bench-batch','prep-drying','method-spectral-import']],
 ['SAMPLE_RECEPTION','Intake officer',['intake-project','intake-draft','intake-location']],
 ['LAB_MANAGER','Laboratory manager',['review-submission','review-assign','review-final']],
 ['PROJECT_MANAGER','Project manager',['connect-project','connect-progress','connect-sis']],
 ['SURVEYOR','Field surveyor',['connect-surveyor','connect-kobo','connect-field-fix']],
 ['AUDIT_USER','Quality & audit reader',['quality-audit','quality-qc','quality-history']],
 ['VIEWER','Laboratory viewer',['start-viewer','tracking-find','review-report']],
 ['EXTERNAL_VIEWER','External report viewer',['review-share','review-report','start-viewer']],
 ['MASTER_USER','Platform coordinator',['admin-catalogue','admin-translation','admin-help']],
 ['SUPER_ADMIN','System administrator',['admin-users','admin-labs','admin-integrations']]
].map(([id,label,tasks]) => ({id,label,tasks,note:'Navigation persona only. The implementation must use actual effective permissions and laboratory/project scope.'}));
const critical = new Set(['start-first-login','start-technician','start-reception','start-manager','start-settings','intake-project','intake-batch','intake-draft','intake-location','intake-analysis','intake-handover','tracking-identifiers','tracking-workspace','tracking-map','prep-drying','prep-preparation','prep-receipt','prep-evidence','bench-batch','bench-paste','bench-states','bench-submit','bench-returned','bench-blocked','method-texture','method-spectral-import','method-spectral-inspect','review-submission','review-final','review-amend','review-report','offline-prepare','offline-record','offline-sync','offline-conflict','offline-account','admin-help','admin-translation','quality-loading','quality-support']);
const inventory = groups.flatMap(group => group.rows.trim().split(/\r?\n/).map(row => {
 const [id,title,outcome,failure,routeText] = row.split('|');
 const exemplar = examples.guides.find(g=>g.id===id);
 return {id,title,topic:group.id,topicTitle:group.title,priority:critical.has(id)?'P0: core continuity and data safety':'P1: required enabled-feature coverage',
  status:exemplar?'ENGLISH_DESIGN_EXEMPLAR_REQUIRES_UI_REVIEW':'COMMISSIONED_WRITING_BRIEF',roles:group.roles,routes:routeText.split(','),outcome,
  failureToExplain:failure,locales:['en','es','es-419','fr','pt'],
  requiredBlocks:['Quick answer','Before you start: identity, permissions and prerequisites','Exact ordered controls and expected outcomes','Fields and synthetic worked example','Check it worked: persisted state and evidence','Recognizable failure and recovery branches','Next actor and next task','Source, release, local SOP and translation metadata'],
  evidenceSources:(exemplar?.sources || group.sources).map(file=>({file,existsAtBuild:fs.existsSync(path.join(root,file)),status:exemplar?'CITED_BY_DESIGN_EXEMPLAR_VERIFY_IN_UI':'CANDIDATE_TO_TRACE_BEFORE_WRITING'})),
  acceptance:['Demonstrate the normal path with representative role fixtures.','Demonstrate the listed failure without inventing a workaround.','Check exact controls, labels, state transitions and all five locale blocks.','Capture synthetic screenshots only after the relevant UI is stable.'],
  scopeNote:'Enabled workflow coverage is mandatory. If a capability is not implemented or not enabled for a lab, document the actual limitation and owner; do not invent the feature.'};
}));
if (new Set(inventory.map(i=>i.id)).size!==inventory.length) throw Error('Duplicate guide identifiers');
const content = {status:'IMPLEMENTATION_BRIEFS_NOT_A_PUBLISHED_CONTENT_RELEASE',count:inventory.length,roles,topics:groups.map(({id,title})=>({id,title})),articles:inventory};
write('04_CONTENT_INVENTORY.json',content);
write('04_CONTENT_INVENTORY.md', '# Commissioned content inventory\n\n'+inventory.length+' distinct task briefs across '+groups.length+' topics. Eight have full English design exemplars; the remainder still require writing and verification. Every active capability needs coverage before final completion. P0 is sequencing, not permission to omit P1. Five complete language versions are required.\n\n'+groups.map(group=>'## '+group.title+'\n\n| Guide | User outcome | Failure to explain | Priority |\n|---|---|---|---|\n'+inventory.filter(i=>i.topic===group.id).map(i=>`| **${i.title}** (${i.id}) | ${i.outcome} | ${i.failureToExplain} | ${i.priority.startsWith('P0')?'P0':'P1'} |`).join('\n')+'\n\nCandidate evidence: '+group.sources.map(s=>'`'+s+'`').join(', ')+'. Verify file existence and follow imports/handlers; candidate references are not proof of behavior.\n').join('\n')+'\nUse the JSON for route associations, full role identifiers, evidence status and acceptance requirements.\n');
write('05_GUIDE_EXAMPLES.md','# Complete English design exemplars\n\n'+examples.note+'\n\nThese eight examples establish the writing standard. They are not a production-reviewed scientific SOP or the entire content collection. Verify source labels and role behavior in the candidate release; record unresolved UI bindings rather than inventing them.\n\n'+examples.guides.map(g=>'## '+g.title+'\n\n`'+g.id+'` · '+g.role+' · '+g.route+'\n\n'+g.summary+'\n\n**Quick answer.** '+g.quick+'\n\n### Before you start\n\n'+g.before.map(t=>'- '+t).join('\n')+'\n\n'+g.sections.map(s=>'### '+s.title+'\n\n'+s.steps.map((st,n)=>(n+1)+'. '+st.action+'\n\n   **What you should see:** '+st.expected).join('\n\n')).join('\n\n')+'\n\n### Field guide\n\n| Field or state | Meaning | Example / instruction |\n|---|---|---|\n'+g.fields.map(row=>'| '+row.join(' | ')+' |').join('\n')+(g.example?'\n\n### Worked example\n\n'+g.example:'')+'\n\n### Check it worked\n\n'+g.success+'\n\n**Who acts next:** '+g.nextActor+'\n\n### If something differs\n\n'+g.problems.map(p=>'**'+p.symptom+'**\n\n'+p.why+'\n\n'+p.action).join('\n\n')+'\n\n### Source evidence to recheck\n\n'+g.sources.map(s=>'- `'+s+'`').join('\n')).join('\n\n---\n\n'));
const app = fs.readFileSync(path.join(root,'client/src/App.jsx'),'utf8');
const routes = [...new Set([...app.matchAll(/<Route\s+path="([^"]+)"/g)].map(m=>m[1]))];
const aliases = {'/my-work':'/workbench','/spectral':'/spectral-library','/reports':'/result-reports','/lab-methods':'/admin/methods','/faq':'/help/faq','/tech-stack':'/techstack','/credits':'/techstack'};
const special = {'/':['start-technician','start-reception','start-manager','start-project','start-auditor','start-viewer'], '/datasheet':['connect-export','connect-field-fix'], '/maps':['connect-map'], '/report/:token':['review-share','review-report'], '/help':['offline-help','start-settings'], '/help/faq':['prep-receipt','bench-states','quality-loading'], '/help/articles/:articleId':['offline-help'], '/help/topics/:topicId':['offline-help']};
const routeMap = routes.map(route=>{
 const canonical = aliases[route]||route;
 const ids = [...new Set([...(special[canonical]||[]),...inventory.filter(i=>i.routes.some(r=>r.split('?')[0]===canonical)).map(i=>i.id)])];
 const institutional=['/about','/techstack','*'].includes(canonical);
 return {route,canonical,guideIds:ids,coverageKind:institutional?'INSTITUTIONAL_OR_NOT_FOUND: provide relevant navigation and public help; not a laboratory procedure':'REQUIRES_ROLE_AND_CONTEXT_VERIFICATION',
  unresolved:!institutional && !ids.length,requirement:'A matching route is only a starting point. Verify permitted recommendations, meaningful deep sections, real query tabs and failure states.'};
});
const contexts = [
 ['/workbench','drying or preparation','prep-drying','prep-receipt'],['/workbench','paste preview and exclusions','bench-paste','bench-batch'],['/workbench','Ready to Submit','bench-submit','bench-states'],['/workbench','spectral input','method-spectral-import','method-spectral-inspect'],['/workbench','texture panel','method-texture','method-derived'],
 ['/samples/:id','work tab','tracking-workspace','prep-receipt'],['/samples/:id','results tab','review-report','review-amend'],['/samples/:id','field data / identity','tracking-identifiers','intake-location'],['/samples/:id/map','blocked node','tracking-map','bench-blocked'],
 ['/manager-queue','intake / assignment','review-intake','review-assign'],['/manager-queue','Review Submissions','review-submission','review-return'],['/manager-queue','Final Approvals','review-final','review-partial'],
 ['/reception','ID & Field / draft','intake-project','intake-location'],['/reception','Condition','intake-condition'],['/reception','Analyses','intake-analysis'],['/reception','Handover','intake-handover'],
 ['/admin','branding','admin-branding'],['/admin','languages','admin-translation'],['/admin','lab-config','admin-catalogue'],['/admin','audit','quality-audit'],['/admin','api-keys','admin-integrations'],['/admin','users','admin-users'],
 ['/admin/help','editor / review / translation / coverage','admin-help','admin-translation'],['/spectral-library','import / inspect','method-spectral-import','method-spectral-inspect'],['/spectral-library','prediction / publishing','method-predictions','method-qc'],['GLOBAL','offline queue / expired session / conflict','offline-sync','offline-account','offline-conflict']
].map(([route,context,...guideIds])=>({route,context,guideIds,status:'PROPOSED_BINDING: resolve actual UI feature/tab keys; validate after implementation'}));
write('traceability.json',{baseline:'6915824',routes:routeMap,contexts,roles,notes:['All App.jsx route declarations are included, including aliases and public routes.','This is a proposed content mapping, not a claim of completed application tests.','Fallback or role-generic links do not count as context coverage.','Public report help must never include the report token in diagnostics, URLs shared with support or analytics.']});
const files = [...new Set(['client/src/App.jsx','server/config/roles.js','client/src/pages/help/HelpCentre.jsx','client/src/pages/help/ArticleReader.jsx','client/src/pages/help/AdminHelpEditor.jsx','server/data/help/content.en.json','server/data/help/content.es.json','server/data/help/content.es-419.json','server/data/help/content.fr.json','server/data/help/content.pt.json','server/data/help/route-help-map.json',...inventory.flatMap(i=>i.evidenceSources.map(s=>s.file))])];
write('source-baseline.json',{generatedAt:new Date().toISOString(),commit:cp.execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),scope:'Read-only evidence snapshot; all changes in WP/help-knowledge-base-v2.',observedContent:{englishArticleCount:27,averageApproximateWords:112,minimumApproximateWords:85,maximumApproximateWords:135,countNote:'Audit of current English title, summary, steps, success and caution fields; not a reading-time claim.'},files:files.map(file=>{const full=path.join(root,file);return !fs.existsSync(full)?{file,status:'CANDIDATE_PATH_NOT_FOUND: resolve actual implementation before writing'}:fs.statSync(full).isDirectory()?{file,status:'CANDIDATE_DIRECTORY: trace the specific handlers and controls'}:{file,sha256:crypto.createHash('sha256').update(fs.readFileSync(full)).digest('hex')};})});
const terms = [
 ['sample','Sample','Muestra','Muestra','Échantillon','Amostra'],['field-id','Field sample ID','ID de muestra de campo','ID de muestra de campo',"Identifiant de l’échantillon de terrain",'ID da amostra de campo'],['lab-id','Laboratory sample ID','ID de muestra de laboratorio','ID de muestra de laboratorio',"Identifiant de l’échantillon de laboratoire",'ID da amostra de laboratório'],
 ['workbench','Workbench','Mesa de trabajo','Mesa de trabajo','Poste de travail','Bancada de trabalho'],['drying','Sample drying','Secado de la muestra','Secado de la muestra',"Séchage de l’échantillon",'Secagem da amostra'],['preparation','Sample preparation','Preparación de la muestra','Preparación de la muestra',"Préparation de l’échantillon",'Preparação da amostra'],
 ['receipt','Confirmation receipt','Comprobante de confirmación','Comprobante de confirmación','Reçu de confirmation','Comprovativo de confirmação'],['local-save','Saved on this device','Guardado en este dispositivo','Guardado en este dispositivo','Enregistré sur cet appareil','Guardado neste dispositivo'],['server-save','Saved on the server','Guardado en el servidor','Guardado en el servidor','Enregistré sur le serveur','Guardado no servidor'],
 ['recorded','Recorded','Registrado','Registrado','Enregistré','Registado'],['submitted','Submitted for review','Enviado a revisión','Enviado a revisión','Soumis à révision','Enviado para revisão'],['accepted','Accepted','Aceptado','Aceptado','Accepté','Aceite'],['report-released','Report released','Informe publicado','Informe publicado','Rapport publié','Relatório publicado'],
 ['texture','Soil texture','Textura del suelo','Textura del suelo','Texture du sol','Textura do solo'],['sand','Sand fraction','Fracción de arena','Fracción de arena','Fraction sableuse','Fração de areia'],['silt','Silt fraction','Fracción de limo','Fracción de limo','Fraction limoneuse','Fração de limo'],['clay','Clay fraction','Fracción de arcilla','Fracción de arcilla','Fraction argileuse','Fração de argila'],
 ['spectrum','Spectrum','Espectro','Espectro','Spectre','Espectro'],['absorbance','Absorbance','Absorbancia','Absorbancia','Absorbance','Absorvância'],['reflectance','Reflectance','Reflectancia','Reflectancia','Réflectance','Refletância'],['qc','Quality control','Control de calidad','Control de calidad','Contrôle qualité','Controlo da qualidade'],['calibration','Calibration','Calibración','Calibración','Étalonnage','Calibração'],['nonconformance','Nonconformance','No conformidad','No conformidad','Non-conformité','Não conformidade'],['replicate','Replicate measurement','Medición replicada','Medición replicada','Mesure répétée','Medição replicada']
].map(([id,en,es,latam,fr,pt])=>({id,status:'DRAFT_TERMINOLOGY_REVIEW_REQUIRED',labels:{en,es,'es-419':latam,fr,pt},note:'Align with the existing application glossary, locale variant and lab review. Do not translate identifiers, formula symbols or numeric storage.'}));
write('terminology.json',{status:'PROPOSED_GLOSSARY_NOT_APPROVED',locales:['en','es','es-419','fr','pt'],terms});
const legacyTargets={
 'start-shift':['start-technician','start-reception','start-manager'], 'intake-project':['intake-project','intake-handover'], 'intake-location':['intake-location','intake-draft'], 'intake-identity':['tracking-identifiers','intake-duplicate'],
 'bench-blocked':['bench-blocked','tracking-map'], 'bench-drying':['prep-drying'], 'bench-preparation':['prep-receipt','prep-preparation'], 'bench-run':['bench-batch','bench-paste'], 'bench-save-submit':['bench-states','bench-submit'], 'bench-texture':['method-texture','method-derived'], 'bench-spectra':['method-spectral-import','method-spectral-inspect'],
 'review-results':['review-submission','review-final'], 'review-returned':['bench-returned','review-return'], 'review-amend':['review-amend'], 'review-report':['review-report','review-share'], 'assets-instrument':['assets-find','assets-calibration','assets-maintain'], 'assets-stock':['assets-stock','assets-trace'],
 'offline-prepare':['offline-prepare','offline-install'], 'offline-sync':['offline-sync','offline-record'], 'offline-files':['offline-record','method-spectral-import'], 'connect-kobo':['connect-kobo','connect-field-fix'], 'connect-library':['method-spectral-inspect','method-predictions'], 'connect-sis':['connect-sis'],
 'manage-catalogue':['admin-catalogue','admin-methods'], 'manage-language':['start-settings','admin-translation'], 'manage-load-error':['quality-loading'], 'manage-support':['quality-support','admin-support']
};
const oldContent=JSON.parse(fs.readFileSync(path.join(root,'server/data/help/content.en.json'),'utf8'));
const migration=oldContent.articles.map(a=>({legacyArticleId:a.articleId||a.id,title:a.title,successorBriefIds:legacyTargets[a.articleId||a.id]||[],identityPolicy:'Retain the existing immutable identity, URL, revisions, feedback and publication history. Brief IDs describe scopes, not compulsory new database identities.',rollout:'Keep the published v1 revision readable until its verified replacement is in the published manifest. Where splitting, preserve the old relevant landing/section and explicit successor links; never redirect all old articles to home.',review:'Rewrite and verify all five locale bodies and figures. Existing v1 publication does not constitute v2 review.'}));
if(migration.some(m=>!m.successorBriefIds.length||m.successorBriefIds.some(id=>!inventory.find(i=>i.id===id))))throw Error('Incomplete legacy migration map');
write('migration-map.json',{status:'PROPOSED_MIGRATION_REQUIRES_CURRENT_DB_ID_VERIFICATION',baseline:'6915824',articles:migration});
write('10_MIGRATION_AND_FAQ.md','# Existing-content migration and FAQ seed\n\n## Preserve every existing article link\n\nThese 27 source article identities are mapped individually. Reconcile with the actual content database before applying changes. Brief IDs are editorial scopes; prefer retaining existing immutable article identities and version histories. If splitting, keep a relevant landing section at the original URL and explicit links to the published successor guides. Do not withdraw all v1 content while v2 is being written.\n\n| Existing ID / title | Replacement scope briefs |\n|---|---|\n'+migration.map(m=>'| `'+m.legacyArticleId+'` — '+m.title+' | '+m.successorBriefIds.map(id=>'`'+id+'`').join(', ')+' |').join('\n')+'\n\n## FAQ entries come from canonical problem blocks\n\nThe following 17 worked question/answer examples are extracted from the eight detailed guides. They establish the minimum practical answer style; all remaining commissioned guides also need their relevant problem blocks. Keep the source block identity and derive the FAQ index at publication, rather than maintaining duplicate editable answers. Only the approved applicable locale should be served.\n\n'+examples.guides.flatMap(g=>g.problems.map((p,i)=>'### '+p.symptom+'\n\n'+p.why+'\n\n**What to do:** '+p.action+'\n\n**Read the steps:** '+g.title+' → If something differs. Canonical source: `'+g.id+'`, proposed stable problem ID `'+g.id+'-problem-'+(i+1)+'`. Assign once and retain across edits.')).join('\n\n'));
const logo = 'data:image/png;base64,'+fs.readFileSync(path.join(root,'client/public/assets/img/soilfer-logo.png')).toString('base64');
const payload = JSON.stringify({content,examples:examples.guides,roles,terms}).replace(/</g,'\\u003c');
write('review-preview.html',fs.readFileSync(path.join(dir,'preview.template.html'),'utf8').replace('__PACKAGE_DATA__',payload).replace('__LOGO_DATA__',logo));
console.log(JSON.stringify({articles:inventory.length,fullEnglishExamples:examples.guides.length,routes:routes.length,unmappedRoutes:routeMap.filter(r=>r.unresolved).map(r=>r.route),output:path.join(dir,'review-preview.html')},null,2));
