/**
 * SoilFER LIMS - Server Theme Catalogue & Validation
 *
 * GENERATED CODE - DO NOT EDIT MANUALLY
 * Source: server/config/themeCatalogData.json (v1.0.0)
 * Generator: server/scripts/generate_theme_catalog.js
 */

const THEME_ALLOWLIST = [
    "soilfer-classic",
    "forest",
    "terra",
    "mineral",
    "watershed",
    "nutrient",
    "clear-contrast"
];

const DEFAULT_THEME_ID = "soilfer-classic";
const DEFAULT_MODE = "light";
const RECOMMENDED_THEME_ID = "forest";
const ACCESSIBILITY_THEME_ID = "clear-contrast";

const SEMANTIC_STATUS = {
    "light": {
        "success": "#246044",
        "successBg": "#EAF4ED",
        "warning": "#7F5710",
        "warningBg": "#FCF2DA",
        "danger": "#9B3842",
        "dangerBg": "#FAEDEF",
        "info": "#206477",
        "infoBg": "#E4F1F3"
    },
    "dark": {
        "success": "#A5DABA",
        "successBg": "#31493B",
        "warning": "#F0D083",
        "warningBg": "#494030",
        "danger": "#F3AFB5",
        "dangerBg": "#4A343B",
        "info": "#9CD4E1",
        "infoBg": "#2E4149"
    }
};

const THEMES = [
    {
        "id": "soilfer-classic",
        "name": "SoilFER Classic",
        "description": "Keep the familiar SoilFER identity.",
        "badge": "Default",
        "light": {
            "canvas": "#F5F3ED",
            "surface": "#FFFFFF",
            "raised": "#FFFFFF",
            "inset": "#F8F7F2",
            "hover": "#EDF4EF",
            "selected": "#EDF4EF",
            "text": "#253A32",
            "muted": "#58665E",
            "divider": "#D9DFD7",
            "border": "#D9DFD7",
            "control": "#7E8C83",
            "primary": "#256348",
            "onPrimary": "#FFFFFF",
            "primaryHover": "#1E523B",
            "sidebar": "#173F32",
            "sideText": "#F3F6EF",
            "sideMuted": "#C4D3CA",
            "sideActive": "#305C49",
            "link": "#206477",
            "focus": "#256348",
            "disabledBg": "#EBEFEC",
            "disabledText": "#617067",
            "chart1": "#256348",
            "chart2": "#206477",
            "chart3": "#945539",
            "browserTheme": "#F5F3ED"
        },
        "dark": {
            "canvas": "#25282B",
            "surface": "#2E3236",
            "raised": "#34393C",
            "inset": "#34393C",
            "hover": "#3C4247",
            "selected": "#344B41",
            "text": "#F1F4F3",
            "muted": "#BBC7C2",
            "divider": "#505C58",
            "border": "#505C58",
            "control": "#8C9B95",
            "primary": "#91D2AF",
            "onPrimary": "#173127",
            "primaryHover": "#A5E0C0",
            "sidebar": "#243932",
            "sideText": "#F1F4F3",
            "sideMuted": "#C4D3CA",
            "sideActive": "#3A5749",
            "link": "#9CD4E1",
            "focus": "#91D2AF",
            "disabledBg": "#3B4145",
            "disabledText": "#C0C8CB",
            "chart1": "#91D2AF",
            "chart2": "#9CD4E1",
            "chart3": "#E6B298",
            "browserTheme": "#25282B"
        }
    },
    {
        "id": "forest",
        "name": "Forest",
        "description": "Soft green and quiet surfaces for everyday soil work.",
        "badge": "Recommended",
        "isRecommended": true,
        "light": {
            "canvas": "#F2F6F1",
            "surface": "#FFFFFF",
            "raised": "#FFFFFF",
            "inset": "#F6FAF5",
            "hover": "#EAF3EC",
            "selected": "#EAF3EC",
            "text": "#253A32",
            "muted": "#58665E",
            "divider": "#D8DFD8",
            "border": "#D8DFD8",
            "control": "#757F78",
            "primary": "#245B3D",
            "onPrimary": "#FFFFFF",
            "primaryHover": "#1D4C32",
            "sidebar": "#1B392B",
            "sideText": "#F3F6EF",
            "sideMuted": "#C3D2C8",
            "sideActive": "#2D5841",
            "link": "#245B3D",
            "focus": "#245B3D",
            "disabledBg": "#E9ECE9",
            "disabledText": "#617067",
            "chart1": "#245B3D",
            "chart2": "#3E7E5A",
            "chart3": "#8C6A48",
            "browserTheme": "#F2F6F1"
        },
        "dark": {
            "canvas": "#252B27",
            "surface": "#303A33",
            "raised": "#303A33",
            "inset": "#37423B",
            "hover": "#3C4940",
            "selected": "#39523F",
            "text": "#F1F4F3",
            "muted": "#BBC7C2",
            "divider": "#526056",
            "border": "#526056",
            "control": "#909D97",
            "primary": "#9DD7AA",
            "onPrimary": "#1B3324",
            "primaryHover": "#B2E4BC",
            "sidebar": "#26382B",
            "sideText": "#F1F4F3",
            "sideMuted": "#C3D2C8",
            "sideActive": "#39523F",
            "link": "#9DD7AA",
            "focus": "#9DD7AA",
            "disabledBg": "#3C453E",
            "disabledText": "#B8C4BD",
            "chart1": "#9DD7AA",
            "chart2": "#6CAE84",
            "chart3": "#D9A984",
            "browserTheme": "#252B27"
        }
    },
    {
        "id": "terra",
        "name": "Terra",
        "description": "Warm clay tones with clear white work surfaces.",
        "light": {
            "canvas": "#F7F2ED",
            "surface": "#FFFFFF",
            "raised": "#FFFFFF",
            "inset": "#FBF7F2",
            "hover": "#F6EDE6",
            "selected": "#F6EDE6",
            "text": "#253A32",
            "muted": "#58665E",
            "divider": "#E2DBD4",
            "border": "#E2DBD4",
            "control": "#757F78",
            "primary": "#865039",
            "onPrimary": "#FFFFFF",
            "primaryHover": "#70402C",
            "sidebar": "#493226",
            "sideText": "#F3F6EF",
            "sideMuted": "#D6CBC4",
            "sideActive": "#6B4938",
            "link": "#865039",
            "focus": "#865039",
            "disabledBg": "#ECE7E2",
            "disabledText": "#617067",
            "chart1": "#865039",
            "chart2": "#B87659",
            "chart3": "#567365",
            "browserTheme": "#F7F2ED"
        },
        "dark": {
            "canvas": "#2C2927",
            "surface": "#3A3330",
            "raised": "#3A3330",
            "inset": "#433B38",
            "hover": "#4C433F",
            "selected": "#54433A",
            "text": "#F1F4F3",
            "muted": "#BBC7C2",
            "divider": "#625853",
            "border": "#625853",
            "control": "#909D97",
            "primary": "#E6B298",
            "onPrimary": "#342821",
            "primaryHover": "#F2C7B3",
            "sidebar": "#3B2E27",
            "sideText": "#F1F4F3",
            "sideMuted": "#D6CBC4",
            "sideActive": "#54433A",
            "link": "#E6B298",
            "focus": "#E6B298",
            "disabledBg": "#433D3A",
            "disabledText": "#B8C4BD",
            "chart1": "#E6B298",
            "chart2": "#D18D6C",
            "chart3": "#8CA698",
            "browserTheme": "#2C2927"
        }
    },
    {
        "id": "mineral",
        "name": "Mineral",
        "description": "Neutral slate for tables, precision and instrument work.",
        "light": {
            "canvas": "#F2F4F6",
            "surface": "#FFFFFF",
            "raised": "#FFFFFF",
            "inset": "#F7F9FA",
            "hover": "#EBF0F4",
            "selected": "#EBF0F4",
            "text": "#253A32",
            "muted": "#58665E",
            "divider": "#D6DCE2",
            "border": "#D6DCE2",
            "control": "#757F78",
            "primary": "#43556D",
            "onPrimary": "#FFFFFF",
            "primaryHover": "#354457",
            "sidebar": "#283545",
            "sideText": "#F3F6EF",
            "sideMuted": "#C5CFD8",
            "sideActive": "#3D4E64",
            "link": "#43556D",
            "focus": "#43556D",
            "disabledBg": "#E6EAEF",
            "disabledText": "#617067",
            "chart1": "#43556D",
            "chart2": "#6A82A0",
            "chart3": "#7D6B58",
            "browserTheme": "#F2F4F6"
        },
        "dark": {
            "canvas": "#272B30",
            "surface": "#333A42",
            "raised": "#333A42",
            "inset": "#3A434C",
            "hover": "#434D57",
            "selected": "#3D4E60",
            "text": "#F1F4F3",
            "muted": "#BBC7C2",
            "divider": "#56626F",
            "border": "#56626F",
            "control": "#909D97",
            "primary": "#ABC2D7",
            "onPrimary": "#232F39",
            "primaryHover": "#C6D8E8",
            "sidebar": "#293440",
            "sideText": "#F1F4F3",
            "sideMuted": "#C5CFD8",
            "sideActive": "#3D4E60",
            "link": "#ABC2D7",
            "focus": "#ABC2D7",
            "disabledBg": "#3D444D",
            "disabledText": "#B8C4BD",
            "chart1": "#ABC2D7",
            "chart2": "#7FA0BE",
            "chart3": "#C4B29E",
            "browserTheme": "#272B30"
        }
    },
    {
        "id": "watershed",
        "name": "Watershed",
        "description": "Restrained teal, suitable for soil and future water analysis.",
        "light": {
            "canvas": "#F0F6F5",
            "surface": "#FFFFFF",
            "raised": "#FFFFFF",
            "inset": "#F5FAFA",
            "hover": "#E6F2F1",
            "selected": "#E6F2F1",
            "text": "#253A32",
            "muted": "#58665E",
            "divider": "#D3DFDE",
            "border": "#D3DFDE",
            "control": "#757F78",
            "primary": "#166879",
            "onPrimary": "#FFFFFF",
            "primaryHover": "#105260",
            "sidebar": "#173F44",
            "sideText": "#F3F6EF",
            "sideMuted": "#C1D4D7",
            "sideActive": "#275B62",
            "link": "#166879",
            "focus": "#166879",
            "disabledBg": "#E7EDEC",
            "disabledText": "#617067",
            "chart1": "#166879",
            "chart2": "#348E9F",
            "chart3": "#826E4A",
            "browserTheme": "#F0F6F5"
        },
        "dark": {
            "canvas": "#252D2E",
            "surface": "#303B3D",
            "raised": "#303B3D",
            "inset": "#384547",
            "hover": "#415052",
            "selected": "#39575B",
            "text": "#F1F4F3",
            "muted": "#BFCBC6",
            "divider": "#526366",
            "border": "#526366",
            "control": "#9AA7A1",
            "primary": "#89CFD2",
            "onPrimary": "#163739",
            "primaryHover": "#A7DFE1",
            "sidebar": "#263C3F",
            "sideText": "#F1F4F3",
            "sideMuted": "#C1D4D7",
            "sideActive": "#39575B",
            "link": "#89CFD2",
            "focus": "#89CFD2",
            "disabledBg": "#3A4547",
            "disabledText": "#B8C4BD",
            "chart1": "#89CFD2",
            "chart2": "#5CAFB3",
            "chart3": "#D5B98A",
            "browserTheme": "#252D2E"
        }
    },
    {
        "id": "nutrient",
        "name": "Nutrient",
        "description": "Muted olive inspired by soil fertility and nutrient work.",
        "light": {
            "canvas": "#F5F5ED",
            "surface": "#FFFFFF",
            "raised": "#FFFFFF",
            "inset": "#FAF9F3",
            "hover": "#EFEFD9",
            "selected": "#EFEFD9",
            "text": "#253A32",
            "muted": "#58665E",
            "divider": "#DCE0CE",
            "border": "#DCE0CE",
            "control": "#757F78",
            "primary": "#596024",
            "onPrimary": "#FFFFFF",
            "primaryHover": "#464C1B",
            "sidebar": "#373B23",
            "sideText": "#F3F6EF",
            "sideMuted": "#CCD1BA",
            "sideActive": "#525936",
            "link": "#596024",
            "focus": "#596024",
            "disabledBg": "#ECEEE3",
            "disabledText": "#617067",
            "chart1": "#596024",
            "chart2": "#7D8837",
            "chart3": "#6C5543",
            "browserTheme": "#F5F5ED"
        },
        "dark": {
            "canvas": "#2A2D25",
            "surface": "#353B2E",
            "raised": "#353B2E",
            "inset": "#3E4536",
            "hover": "#47503E",
            "selected": "#465536",
            "text": "#F1F4F3",
            "muted": "#BBC7C2",
            "divider": "#5C6551",
            "border": "#5C6551",
            "control": "#96A39D",
            "primary": "#C4D48E",
            "onPrimary": "#30381C",
            "primaryHover": "#D5E3A5",
            "sidebar": "#303A25",
            "sideText": "#F1F4F3",
            "sideMuted": "#CCD1BA",
            "sideActive": "#465536",
            "link": "#C4D48E",
            "focus": "#C4D48E",
            "disabledBg": "#404639",
            "disabledText": "#B8C4BD",
            "chart1": "#C4D48E",
            "chart2": "#9FBA5A",
            "chart3": "#BFA48A",
            "browserTheme": "#2A2D25"
        }
    },
    {
        "id": "clear-contrast",
        "name": "Clear Contrast",
        "description": "Stronger edges and text with minimal decoration.",
        "badge": "Accessibility",
        "isAccessibility": true,
        "light": {
            "canvas": "#FFFFFF",
            "surface": "#FFFFFF",
            "raised": "#FFFFFF",
            "inset": "#F7F7F7",
            "hover": "#ECECEC",
            "selected": "#E5EFF7",
            "text": "#111111",
            "muted": "#303030",
            "divider": "#404040",
            "border": "#404040",
            "control": "#404040",
            "primary": "#003E70",
            "onPrimary": "#FFFFFF",
            "primaryHover": "#002D52",
            "sidebar": "#182B3B",
            "sideText": "#FFFFFF",
            "sideMuted": "#E0E0E0",
            "sideActive": "#003E70",
            "link": "#003E70",
            "focus": "#003E70",
            "disabledBg": "#E0E0E0",
            "disabledText": "#454545",
            "chart1": "#003E70",
            "chart2": "#5E2750",
            "chart3": "#8C4400",
            "browserTheme": "#FFFFFF"
        },
        "dark": {
            "canvas": "#161616",
            "surface": "#202020",
            "raised": "#202020",
            "inset": "#282828",
            "hover": "#323232",
            "selected": "#243545",
            "text": "#FFFFFF",
            "muted": "#DEDEDE",
            "divider": "#C0C0C0",
            "border": "#C0C0C0",
            "control": "#C0C0C0",
            "primary": "#90C9FF",
            "onPrimary": "#102A40",
            "primaryHover": "#B8DCFF",
            "sidebar": "#202020",
            "sideText": "#FFFFFF",
            "sideMuted": "#DEDEDE",
            "sideActive": "#2C4054",
            "link": "#90C9FF",
            "focus": "#90C9FF",
            "disabledBg": "#383838",
            "disabledText": "#C0C0C0",
            "chart1": "#90C9FF",
            "chart2": "#F0A6E0",
            "chart3": "#FFB366",
            "browserTheme": "#161616"
        }
    }
];

const THEME_MAP = new Map(THEMES.map(t => [t.id, t]));

function isValidThemeId(id) {
    return typeof id === 'string' && THEME_MAP.has(id);
}

function isValidMode(mode) {
    return mode === 'light' || mode === 'dark';
}

function isValidModePreference(pref) {
    return pref === 'inherit' || pref === 'light' || pref === 'dark';
}

function getTheme(themeId) {
    return THEME_MAP.get(themeId) || THEME_MAP.get(DEFAULT_THEME_ID);
}

function getPublishedThemeList() {
    return THEMES.map(t => ({
        id: t.id,
        name: t.name,
        description: t.description,
        badge: t.badge || null,
        isRecommended: !!t.isRecommended,
        isAccessibility: !!t.isAccessibility,
        lightSwatches: t.light,
        darkSwatches: t.dark
    }));
}

module.exports = {
    THEME_ALLOWLIST,
    DEFAULT_THEME_ID,
    DEFAULT_MODE,
    RECOMMENDED_THEME_ID,
    ACCESSIBILITY_THEME_ID,
    SEMANTIC_STATUS,
    THEMES,
    isValidThemeId,
    isValidMode,
    isValidModePreference,
    getTheme,
    getPublishedThemeList
};
