/**
 * i18nHelper.js
 * 
 * Central utility for translating dynamic entity names and status labels.
 * Works with the translation keys generated by TranslationService on the backend.
 */

/**
 * Get the translated display name for a dynamic entity (analysis, gate, category, etc.)
 * Falls back to the entity's native name if no translation exists.
 * 
 * @param {Object} entity - Entity with `code` and `name` properties
 * @param {string} type   - One of: 'analysis', 'gate', 'category', 'equipmentType'
 * @param {Function} t    - Translation function from useLanguage()
 * @returns {string}
 */
export const getTranslatedName = (entity, type, t) => {
    if (!entity) return '';
    const code = entity.code || entity.id;
    if (!code) return entity.name || '';

    const key = `dynamic.${type}.${code}.name`;
    const translated = t(key);
    // If t() returns the key itself, it means no translation exists — use native name
    return translated === key ? (entity.name || code) : translated;
};

/**
 * Status code → translation key mapping.
 * Covers both sample-level and work-item-level statuses.
 */
const STATUS_KEYS = {
    // Sample statuses
    EXPECTED: 'status.EXPECTED',
    DRAFT: 'status.DRAFT',
    COLLECTED: 'status.COLLECTED',
    RECEIVED: 'status.RECEIVED',
    ACCEPTED: 'status.ACCEPTED',
    LAB_ID_ASSIGNED: 'status.LAB_ID_ASSIGNED',
    DRYING: 'status.DRYING',
    PREPARED: 'status.PREPARED',
    PROCESSING: 'status.PROCESSING',
    WET_CHEM_IN_PROGRESS: 'status.WET_CHEM_IN_PROGRESS',
    WET_CHEM_COMPLETED: 'status.WET_CHEM_COMPLETED',
    SPECTRAL_IN_PROGRESS: 'status.SPECTRAL_IN_PROGRESS',
    SPECTRAL_COMPLETED: 'status.SPECTRAL_COMPLETED',
    QA_QC_IN_PROGRESS: 'status.QA_QC_IN_PROGRESS',
    ANALYSIS_COMPLETED: 'status.ANALYSIS_COMPLETED',
    COMPLETED: 'status.COMPLETED',
    APPROVED: 'status.APPROVED',
    REJECTED: 'status.REJECTED',
    ARCHIVED: 'status.ARCHIVED',
    DISPOSED: 'status.DISPOSED',
    RETURNED: 'status.RETURNED',
    // Work item statuses
    IN_PROGRESS: 'status.IN_PROGRESS',
    PENDING_RESULT: 'status.PENDING_RESULT',
    REVIEW_PENDING: 'status.REVIEW_PENDING',
    BLOCKED: 'status.BLOCKED',
    ASSIGNED: 'status.ASSIGNED',
    // Submission statuses
    PENDING: 'status.PENDING',
    SUBMITTED: 'status.SUBMITTED',
};

/**
 * Get a localized label for a status code.
 * Falls back to a title-cased version of the raw status if no translation exists.
 * 
 * @param {string} status - Status code (e.g. 'RECEIVED', 'IN_PROGRESS')
 * @param {Function} t    - Translation function from useLanguage()
 * @returns {string}
 */
export const getStatusLabel = (status, t) => {
    if (!status) return '';
    const key = STATUS_KEYS[status];
    if (!key) {
        // Fallback: convert UPPER_SNAKE to Title Case
        return status.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()).toLowerCase()
            .replace(/\b\w/g, c => c.toUpperCase());
    }
    const translated = t(key);
    return translated === key ? status.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()) : translated;
};

/**
 * Format a date according to the user's locale.
 * 
 * @param {string|Date} date   - Date to format
 * @param {string} locale      - BCP 47 locale (e.g. 'en', 'fr', 'pt')
 * @param {Object} options     - Intl.DateTimeFormat options
 * @returns {string}
 */
export const formatLocalDate = (date, locale = 'en', options = {}) => {
    if (!date) return '';
    try {
        const d = typeof date === 'string' ? new Date(date) : date;
        const defaults = {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
            ...options
        };
        return new Intl.DateTimeFormat(locale, defaults).format(d);
    } catch {
        return String(date);
    }
};

/**
 * Format a date with time.
 */
export const formatLocalDateTime = (date, locale = 'en') => {
    return formatLocalDate(date, locale, {
        hour: '2-digit',
        minute: '2-digit'
    });
};

/**
 * Format a number according to locale.
 */
export const formatLocalNumber = (num, locale = 'en', options = {}) => {
    if (num === null || num === undefined) return '';
    try {
        return new Intl.NumberFormat(locale, options).format(num);
    } catch {
        return String(num);
    }
};
