import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

// --- CSV FORMATTER ---
export const generateCSV = (data, columns, meta, filename = 'export.csv') => {
    // 1. Metadata Block
    const metaBlock = [
        `# SOILFER-LIMS EXPORT`,
        `# Export ID: ${meta.exportId}`,
        `# Generated At: ${meta.generatedAt}`,
        `# Generated By: ${meta.generatedBy}`,
        `# Scope: ${JSON.stringify(meta.filters)}`,
        `# ------------------------------------------------`
    ].join('\n');

    // 2. Header
    const header = columns.join(',');

    // 3. Rows
    const rows = data.map(row => {
        return columns.map(col => {
            let val = row[col];
            if (val === null || val === undefined) val = '';
            // Escape quotes
            if (typeof val === 'string' && (val.includes(',') || val.includes('"') || val.includes('\n'))) {
                val = `"${val.replace(/"/g, '""')}"`;
            }
            return val;
        }).join(',');
    }).join('\n');

    const csvContent = `${metaBlock}\n${header}\n${rows}`;
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    triggerDownload(blob, filename);
};

// --- XLS (XML) FORMATTER ---
export const generateXLS = (data, columns, meta, filename = 'export.xls') => {
    const createCell = (val, styleID) => {
        const type = typeof val === 'number' ? 'Number' : 'String';
        const styleAttr = styleID ? ` ss:StyleID="${styleID}"` : '';
        return `<Cell${styleAttr}><Data ss:Type="${type}">${val === null || val === undefined ? '' : val}</Data></Cell>`;
    };

    const createRow = (row) => {
        const cells = columns.map(col => createCell(row[col]));
        return `<Row>${cells.join('')}</Row>`;
    };

    // Header Style
    const styles = `
    <Styles>
     <Style ss:ID="sHeader">
      <Font ss:Bold="1"/>
      <Interior ss:Color="#C0C0C0" ss:Pattern="Solid"/>
     </Style>
    </Styles>`;

    const headerRow = `<Row>${columns.map(c => createCell(c, 'sHeader')).join('')}</Row>`;
    const dataRows = data.map(createRow).join('\n');

    // Metadata Sheet
    const metaRows = Object.entries(meta).map(([k, v]) => {
        if (k === 'analysisMetadata') return ''; // Handle separately
        return `<Row><Cell><Data ss:Type="String">${k}</Data></Cell><Cell><Data ss:Type="String">${typeof v === 'object' ? JSON.stringify(v) : v}</Data></Cell></Row>`;
    }).join('');

    // Methods Sheet
    let methodsRows = '';
    if (meta.analysisMetadata) {
        methodsRows = Object.entries(meta.analysisMetadata).map(([code, info]) => {
            return `<Row>
                <Cell><Data ss:Type="String">${code}</Data></Cell>
                <Cell><Data ss:Type="String">${info.name || ''}</Data></Cell>
                <Cell><Data ss:Type="String">${info.unit || ''}</Data></Cell>
                <Cell><Data ss:Type="String">${info.method || ''}</Data></Cell>
            </Row>`;
        }).join('\n');
    }
    const methodsHeader = `<Row>
        <Cell ss:StyleID="sHeader"><Data ss:Type="String">Analysis Code</Data></Cell>
        <Cell ss:StyleID="sHeader"><Data ss:Type="String">Name</Data></Cell>
        <Cell ss:StyleID="sHeader"><Data ss:Type="String">Unit</Data></Cell>
        <Cell ss:StyleID="sHeader"><Data ss:Type="String">Methodology</Data></Cell>
    </Row>`;

    const xml = `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
 ${styles}
 <Worksheet ss:Name="Results">
  <Table>
   ${headerRow}
   ${dataRows}
  </Table>
 </Worksheet>
 <Worksheet ss:Name="Export Metadata">
  <Table>
   <Row><Cell ss:StyleID="sHeader"><Data ss:Type="String">Meta Key</Data></Cell><Cell ss:StyleID="sHeader"><Data ss:Type="String">Value</Data></Cell></Row>
   ${metaRows}
  </Table>
 </Worksheet>
 <Worksheet ss:Name="Methods & Units">
  <Table>
   ${methodsHeader}
   ${methodsRows}
  </Table>
 </Worksheet>
</Workbook>`;

    const blob = new Blob([xml], { type: 'application/vnd.ms-excel' });
    triggerDownload(blob, filename);
};

// --- PDF FORMATTER ---
export const generatePDF = (data, columns, meta, filename = 'export.pdf') => {
    const doc = new jsPDF('l', 'mm', 'a4'); // Landscape

    // Brand Colors
    const primaryColor = [41, 128, 185]; // Blue

    // Header
    doc.setFontSize(18);
    doc.setTextColor(...primaryColor);
    doc.text('SOILFER-LIMS Official Report', 14, 15);

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Export ID: ${meta.exportId}`, 14, 25);
    doc.text(`Generated: ${new Date(meta.generatedAt).toLocaleString()}`, 14, 30);
    doc.text(`Authorized By: ${meta.generatedBy}`, 14, 35);
    doc.text(`Filters: ${JSON.stringify(meta.filters)}`, 14, 40);

    // AutoTable
    const tableRows = data.map(row => columns.map(col => row[col] || ''));

    doc.autoTable({
        head: [columns],
        body: tableRows,
        startY: 50,
        styles: { fontSize: 7, cellPadding: 1 },
        headStyles: { fillColor: primaryColor, textColor: 255, fontSize: 8 },
        theme: 'grid'
    });

    // Signature Block (Mandatory)
    const pageCount = doc.internal.getNumberOfPages();
    doc.setPage(pageCount);
    const finalY = doc.lastAutoTable.finalY || 50;

    const sigY = finalY > 150 ? 170 : finalY + 30; // Force bottom area if space, or guaranteed logical placement

    doc.setDrawColor(0);
    doc.line(14, sigY, 80, sigY); // Line
    doc.setFontSize(10);
    doc.text('Authorized & Signed', 14, sigY + 5);
    doc.setFont('helvetica', 'bold');
    doc.text(meta.generatedBy || 'System', 14, sigY + 10);
    doc.setFont('helvetica', 'normal');
    doc.text('Terms: This document is an official export of SoilFER-LIMS.', 14, sigY + 20);
    doc.text('Results are strictly based on approved samples.', 14, sigY + 25);

    doc.save(filename);
};

const triggerDownload = (blob, filename) => {
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
};
