// Standalone artifact checks in an isolated headless browser; no signed-in profile.
const { chromium } = require('C:/Users/yigin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path = require('path'), fs = require('fs'), assert = require('assert');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1080}}), errors=[], requests=[];
 page.on('pageerror',e=>errors.push(e.message)); page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});
 await page.goto('file:///'+path.join(__dirname,'review-preview.html').replaceAll('\\','/'));
 await page.screenshot({path:path.join(__dirname,'preview-desktop-list.png'),fullPage:true});
 await page.getByRole('button',{name:'Open →',exact:true}).first().click();
 await page.screenshot({path:path.join(__dirname,'preview-desktop-workspace.png'),fullPage:true});
 await page.getByRole('button',{name:'Awaiting arrival',exact:false}).click();
 assert(await page.getByText('40 matching samples',{exact:false}).count());
 for(const tab of ['Analysis plan','Labs & people','Data connections','Activity','Overview']) await page.getByRole('button',{name:tab,exact:true}).click();
 await page.getByRole('button',{name:'Data connections',exact:true}).click();
 await page.getByRole('button',{name:'Preview a manifest',exact:true}).click();
 await page.getByRole('button',{name:'Check rows',exact:true}).click();
 assert(await page.getByText('2 rows ready',{exact:false}).count());
 await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.getByRole('button',{name:'Project actions',exact:false}).click();
 await page.getByRole('button',{name:'Review archival readiness',exact:false}).click();
 assert(await page.getByRole('heading',{name:'This project is not ready to archive'}).count());
 await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.getByRole('button',{name:'Project actions',exact:false}).click();
 await page.getByRole('button',{name:'Pause new admissions',exact:false}).click();
 await page.getByLabel('Reason',{exact:true}).fill('Demo shipment delay');
 await page.getByRole('button',{name:'Confirm in demo',exact:true}).click();
 assert(await page.getByText('Paused',{exact:true}).count());
 await page.getByRole('combobox',{name:'View as',exact:true}).selectOption('service');
 assert.equal(await page.getByRole('button',{name:'Project actions',exact:false}).count(),0);
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 assert(await page.getByText('40 registered in your laboratory',{exact:false}).count());
 await page.getByRole('button',{name:'Dark gray',exact:true}).click();
 await page.evaluate(()=>document.getElementById('toast').hidden=true);
 await page.screenshot({path:path.join(__dirname,'preview-dark.png'),fullPage:true});
 await page.getByRole('button',{name:'Dark gray',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(__dirname,'preview-mobile.png'),fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 assert.equal(overflow,false,'Mobile page must not overflow');
 await page.getByRole('button',{name:'Samples & arrivals',exact:true}).click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.setViewportSize({width:1440,height:1080});
 await page.getByRole('combobox',{name:'View as',exact:true}).selectOption('owner');
 await page.getByRole('button',{name:'Reset demo',exact:true}).click();
 await page.getByRole('button',{name:'+ New project',exact:true}).click();
 await page.getByLabel('Project name',{exact:true}).fill('QA draft');
 await page.getByLabel('Permanent project code',{exact:true}).fill('QA-DRAFT');
 await page.getByRole('button',{name:'Create demo draft',exact:true}).click();
 await page.getByRole('button',{name:'Open →',exact:true}).last().click();
 assert(await page.getByText('0 registered samples.',{exact:false}).count());
 assert.deepEqual(errors,[]); assert.deepEqual(requests,[]);
 fs.writeFileSync(path.join(__dirname,'preview-qa-results.json'),JSON.stringify({checkedAt:new Date().toISOString(),passed:true,browser:'Isolated headless Chrome',viewports:['1440x1080','390x844'],checks:['six tabs','sample stage drilldown','manifest duplicate/leading-zero preview','archive blocker','reasoned admissions pause','role-specific actions and counts','light/dark screenshots','mobile overflow','empty draft creation','no runtime errors','no HTTP requests'],errors,requests},null,2));
 await browser.close(); console.log('Preview checks passed. Screenshots saved in WP package.');
})().catch(e=>{console.error(e);process.exit(1)});
