CREATE TRIGGER "Sample_status_insert_guard" BEFORE INSERT ON "Sample"
WHEN NEW.status IS NULL OR NEW.status NOT IN ('DRAFT','EXPECTED','RECEIVED','ACCEPTED','PROCESSING','SUBMITTED_PARTIAL','SUBMITTED_FULL','APPROVED','ARCHIVED','DISPOSED','RECEIVED_REJECTED','ON_HOLD','CANCELLED')
BEGIN SELECT RAISE(ABORT, 'INVALID_SAMPLE_STATUS'); END;

CREATE TRIGGER "Sample_status_update_guard" BEFORE UPDATE OF "status" ON "Sample"
WHEN NEW.status IS NOT OLD.status AND (NEW.status IS NULL OR (
 NEW.status NOT IN ('DRAFT','EXPECTED','RECEIVED','ACCEPTED','PROCESSING','SUBMITTED_PARTIAL','SUBMITTED_FULL','APPROVED','ARCHIVED','DISPOSED','RECEIVED_REJECTED','ON_HOLD','CANCELLED')
 AND NOT (OLD.legacyStatus IS NOT NULL AND NEW.status = OLD.legacyStatus AND NEW.legacyStatus IS NULL)))
BEGIN SELECT RAISE(ABORT, 'INVALID_SAMPLE_STATUS'); END;

CREATE TRIGGER "WorkItem_status_insert_guard" BEFORE INSERT ON "WorkItem"
WHEN NEW.status IS NULL OR NEW.status NOT IN ('NOT_ASSIGNED','ASSIGNED','IN_PROGRESS','COMPLETED','SUBMITTED','ACCEPTED','REPEAT_REQUIRED','REANALYSIS_REQUIRED','WAIVED','ON_HOLD','AWAITING_VERIFICATION','CANCELLED')
BEGIN SELECT RAISE(ABORT, 'INVALID_WORKITEM_STATUS'); END;

CREATE TRIGGER "WorkItem_status_update_guard" BEFORE UPDATE OF "status" ON "WorkItem"
WHEN NEW.status IS NOT OLD.status AND (NEW.status IS NULL OR (
 NEW.status NOT IN ('NOT_ASSIGNED','ASSIGNED','IN_PROGRESS','COMPLETED','SUBMITTED','ACCEPTED','REPEAT_REQUIRED','REANALYSIS_REQUIRED','WAIVED','ON_HOLD','AWAITING_VERIFICATION','CANCELLED')
 AND NOT (OLD.legacyStatus IS NOT NULL AND NEW.status = OLD.legacyStatus AND NEW.legacyStatus IS NULL)))
BEGIN SELECT RAISE(ABORT, 'INVALID_WORKITEM_STATUS'); END;

CREATE TRIGGER "Batch_status_insert_guard" BEFORE INSERT ON "Batch"
WHEN NEW.status IS NULL OR NEW.status NOT IN ('OPEN','RUNNING','QC_PASS','QC_FAIL','CLOSED')
BEGIN SELECT RAISE(ABORT, 'INVALID_BATCH_STATUS'); END;
CREATE TRIGGER "Batch_status_update_guard" BEFORE UPDATE OF "status" ON "Batch"
WHEN NEW.status IS NOT OLD.status AND (NEW.status IS NULL OR NEW.status NOT IN ('OPEN','RUNNING','QC_PASS','QC_FAIL','CLOSED'))
BEGIN SELECT RAISE(ABORT, 'INVALID_BATCH_STATUS'); END;

CREATE TRIGGER "ReviewDecision_decision_insert_guard" BEFORE INSERT ON "ReviewDecision"
WHEN NEW.decision IS NULL OR NEW.decision NOT IN ('ACCEPT','RETURN','REJECT','OMIT')
BEGIN SELECT RAISE(ABORT, 'INVALID_REVIEW_DECISION'); END;
CREATE TRIGGER "ReviewDecision_decision_immutable" BEFORE UPDATE OF "decision" ON "ReviewDecision"
BEGIN SELECT RAISE(ABORT, 'REVIEW_DECISION_IMMUTABLE'); END;

CREATE TRIGGER "ResultEvidenceEvent_insert_guard" BEFORE INSERT ON "ResultEvidenceEvent"
WHEN NEW.eventType NOT IN ('PREP_REVERTED','PREP_REVERT_CLEARED')
 OR NEW.gate NOT IN ('DRYING','PREPARATION') OR LENGTH(TRIM(NEW.reason)) = 0 OR LENGTH(TRIM(NEW.actor)) = 0
 OR NOT EXISTS (SELECT 1 FROM "Result" WHERE id = NEW.resultId AND sampleId = NEW.sampleId)
BEGIN SELECT RAISE(ABORT, 'INVALID_RESULT_EVIDENCE'); END;
CREATE TRIGGER "ResultEvidenceEvent_update_immutable" BEFORE UPDATE ON "ResultEvidenceEvent"
BEGIN SELECT RAISE(ABORT, 'RESULT_EVIDENCE_IMMUTABLE'); END;
CREATE TRIGGER "ResultEvidenceEvent_delete_immutable" BEFORE DELETE ON "ResultEvidenceEvent"
BEGIN SELECT RAISE(ABORT, 'RESULT_EVIDENCE_IMMUTABLE'); END;
