export const chapters = [
    {
        id: 'welcome',
        nameKey: 'chapters.welcome.name',
        roleKey: 'roles.visitor',
        route: '/login',
        routeDisplay: '/login',
        targetAnchor: '[data-tour="login-form"]',
        requiredPermission: null,
        titleKey: 'chapters.welcome.title',
        copyKey: 'chapters.welcome.copy',
        whyKey: 'chapters.welcome.why',
        nextKey: 'chapters.welcome.next',
        resolveRoute: () => '/login'
    },
    {
        id: 'identity',
        nameKey: 'chapters.identity.name',
        roleKey: 'roles.visitor',
        route: '/',
        routeDisplay: '/login → /',
        targetAnchor: '[data-tour="nav-dashboard"]',
        requiredPermission: null,
        titleKey: 'chapters.identity.title',
        copyKey: 'chapters.identity.copy',
        whyKey: 'chapters.identity.why',
        nextKey: 'chapters.identity.next',
        resolveRoute: (ctx) => ctx && ctx.isAuthenticated ? '/' : '/login'
    },
    {
        id: 'field',
        nameKey: 'chapters.field.name',
        roleKey: 'roles.reception',
        route: '/projects',
        routeDisplay: '/projects',
        targetAnchor: '[data-tour="projects-container"]',
        requiredPermission: 'VIEW_PROJECTS',
        titleKey: 'chapters.field.title',
        copyKey: 'chapters.field.copy',
        whyKey: 'chapters.field.why',
        nextKey: 'chapters.field.next',
        resolveRoute: () => '/projects'
    },
    {
        id: 'intake',
        nameKey: 'chapters.intake.name',
        roleKey: 'roles.reception',
        route: '/reception',
        routeDisplay: '/reception',
        targetAnchor: '[data-tour="reception-container"]',
        requiredPermission: 'RECEIVE_SAMPLE',
        titleKey: 'chapters.intake.title',
        copyKey: 'chapters.intake.copy',
        whyKey: 'chapters.intake.why',
        nextKey: 'chapters.intake.next',
        practiceType: 'intake',
        resolveRoute: () => '/reception'
    },
    {
        id: 'receipt',
        nameKey: 'chapters.receipt.name',
        roleKey: 'roles.reception',
        route: '/reception',
        routeDisplay: '/reception',
        targetAnchor: '[data-tour="reception-container"]',
        requiredPermission: 'RECEIVE_SAMPLE',
        titleKey: 'chapters.receipt.title',
        copyKey: 'chapters.receipt.copy',
        whyKey: 'chapters.receipt.why',
        nextKey: 'chapters.receipt.next',
        practiceType: 'receipt',
        resolveRoute: () => '/reception'
    },
    {
        id: 'assignment',
        nameKey: 'chapters.assignment.name',
        roleKey: 'roles.manager',
        route: '/manager-queue?lane=assign',
        routeDisplay: '/manager-queue?lane=assign',
        targetAnchor: '[data-tour="manager-queue-container"]',
        requiredPermission: 'APPROVE_RESULTS',
        titleKey: 'chapters.assignment.title',
        copyKey: 'chapters.assignment.copy',
        whyKey: 'chapters.assignment.why',
        nextKey: 'chapters.assignment.next',
        practiceType: 'assignment',
        resolveRoute: () => '/manager-queue?lane=assign'
    },
    {
        id: 'equipment',
        nameKey: 'chapters.equipment.name',
        roleKey: 'roles.technician',
        route: '/equipment',
        routeDisplay: '/equipment',
        targetAnchor: '[data-tour="equipment-container"]',
        requiredPermission: 'VIEW_EQUIPMENT',
        titleKey: 'chapters.equipment.title',
        copyKey: 'chapters.equipment.copy',
        whyKey: 'chapters.equipment.why',
        nextKey: 'chapters.equipment.next',
        practiceType: 'resources',
        resolveRoute: () => '/equipment'
    },
    {
        id: 'inventory',
        nameKey: 'chapters.inventory.name',
        roleKey: 'roles.technician',
        route: '/inventory',
        routeDisplay: '/inventory',
        targetAnchor: '[data-tour="inventory-container"]',
        requiredPermission: 'VIEW_INVENTORY',
        titleKey: 'chapters.inventory.title',
        copyKey: 'chapters.inventory.copy',
        whyKey: 'chapters.inventory.why',
        nextKey: 'chapters.inventory.next',
        practiceType: 'resources',
        resolveRoute: () => '/inventory'
    },
    {
        id: 'prepare',
        nameKey: 'chapters.prepare.name',
        roleKey: 'roles.technician',
        route: '/workbench',
        routeDisplay: '/workbench',
        targetAnchor: '[data-tour="workbench-container"]',
        requiredPermission: 'ENTER_RESULTS',
        titleKey: 'chapters.prepare.title',
        copyKey: 'chapters.prepare.copy',
        whyKey: 'chapters.prepare.why',
        nextKey: 'chapters.prepare.next',
        practiceType: 'prepare',
        resolveRoute: () => '/workbench'
    },
    {
        id: 'bench',
        nameKey: 'chapters.bench.name',
        roleKey: 'roles.technician',
        route: '/workbench',
        routeDisplay: '/workbench',
        targetAnchor: '[data-tour="workbench-container"]',
        requiredPermission: 'ENTER_RESULTS',
        titleKey: 'chapters.bench.title',
        copyKey: 'chapters.bench.copy',
        whyKey: 'chapters.bench.why',
        nextKey: 'chapters.bench.next',
        practiceType: 'bench',
        resolveRoute: () => '/workbench'
    },
    {
        id: 'texture',
        nameKey: 'chapters.texture.name',
        roleKey: 'roles.technician',
        route: '/workbench',
        routeDisplay: '/workbench',
        targetAnchor: '[data-tour="workbench-container"]',
        requiredPermission: 'ENTER_RESULTS',
        titleKey: 'chapters.texture.title',
        copyKey: 'chapters.texture.copy',
        whyKey: 'chapters.texture.why',
        nextKey: 'chapters.texture.next',
        practiceType: 'texture',
        resolveRoute: () => '/workbench'
    },
    {
        id: 'spectra',
        nameKey: 'chapters.spectra.name',
        roleKey: 'roles.technician',
        route: '/spectral-library',
        routeDisplay: '/spectral-library',
        targetAnchor: '[data-tour="spectral-library-container"]',
        requiredPermission: 'ENTER_RESULTS',
        titleKey: 'chapters.spectra.title',
        copyKey: 'chapters.spectra.copy',
        whyKey: 'chapters.spectra.why',
        nextKey: 'chapters.spectra.next',
        practiceType: 'spectra',
        resolveRoute: () => '/spectral-library'
    },
    {
        id: 'review',
        nameKey: 'chapters.review.name',
        roleKey: 'roles.manager',
        route: '/manager-queue?lane=review',
        routeDisplay: '/manager-queue?lane=review',
        targetAnchor: '[data-tour="manager-queue-container"]',
        requiredPermission: 'APPROVE_RESULTS',
        titleKey: 'chapters.review.title',
        copyKey: 'chapters.review.copy',
        whyKey: 'chapters.review.why',
        nextKey: 'chapters.review.next',
        practiceType: 'review',
        resolveRoute: () => '/manager-queue?lane=review'
    },
    {
        id: 'trace',
        nameKey: 'chapters.trace.name',
        roleKey: 'roles.manager',
        route: '/workflow-map',
        routeDisplay: '/samples/:id/map',
        targetAnchor: '[data-tour="workflow-map-container"]',
        requiredPermission: 'VIEW_SAMPLES',
        titleKey: 'chapters.trace.title',
        copyKey: 'chapters.trace.copy',
        whyKey: 'chapters.trace.why',
        nextKey: 'chapters.trace.next',
        resolveRoute: (ctx) => {
            if (ctx && ctx.selectedSampleId) {
                return `/samples/${encodeURIComponent(ctx.selectedSampleId)}/map`;
            }
            return null;
        }
    },
    {
        id: 'reports',
        nameKey: 'chapters.reports.name',
        roleKey: 'roles.manager',
        route: '/result-reports',
        routeDisplay: '/result-reports',
        targetAnchor: '[data-tour="result-reports-container"]',
        requiredPermission: 'GENERATE_REPORT',
        titleKey: 'chapters.reports.title',
        copyKey: 'chapters.reports.copy',
        whyKey: 'chapters.reports.why',
        nextKey: 'chapters.reports.next',
        resolveRoute: () => '/result-reports'
    },
    {
        id: 'finish',
        nameKey: 'chapters.finish.name',
        roleKey: 'roles.assigned',
        route: '/help',
        routeDisplay: '/help',
        targetAnchor: '[data-tour="help-container"]',
        requiredPermission: null,
        titleKey: 'chapters.finish.title',
        copyKey: 'chapters.finish.copy',
        whyKey: 'chapters.finish.why',
        nextKey: 'chapters.finish.next',
        resolveRoute: () => '/help'
    }
];
